/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnimateList: typeof import('./../src/components/animateList.vue')['default']
    ArticleList: typeof import('./../src/components/articleList.vue')['default']
    BreadCrumb: typeof import('./../src/components/BreadCrumb.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    FormHpButton: typeof import('./../src/components/form/hp-button.vue')['default']
    FormHpInput: typeof import('./../src/components/form/hp-input.vue')['default']
    FormHpLink: typeof import('./../src/components/form/hp-link.vue')['default']
    MarkdownEditor: typeof import('./../src/components/markdown/editor.vue')['default']
    Notification: typeof import('./../src/components/Notification.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WangEditorEditor: typeof import('./../src/components/wangEditor/editor.vue')['default']
  }
}
